# Generated by Django 5.1.7 on 2026-04-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
        ("clinicians", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="appointment",
            name="appointment_patient_42b596_idx",
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("patient", "scheduled_at"), name="appointment_patient_scheduled_uniq"
            ),
        ),
    ]
